databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: spoti-fejk
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase;
        name: postgres
        proprety: connectionString
    